# Dependencies
markdown:         kramdown
kramdown:
  parse_block_html: true 
highlighter:      pygments

# Permalinks
permalink:            date
paginate_path:        /page:num
relative_permalinks:  true

# Setup
title:            'Jeffrey W. Hollister'
tagline:          ''
description:      'Landscape Ecology, Lakes, GIS, R, and Open Science'
url:              http://jwhollister.com
baseurl:          /

author:
  name:           'Jeffrey W. Hollister'
  url:            https://twitter.com/jhollist

paginate:         5

timezone:         America/New_York

# Custom vars
version:          0.2.0

logos:
  - site:     https://twitter.com/jhollist
    img:      public/images/Twitter_logo_blue.png
  - site:     https://impactstory.org/JeffreyHollister/
    img:      public/images/impactstory-logo-no-type.png   
  - site:     http://scholar.google.com/citations?user=Fn9BjfIAAAAJ&hl=en
    img:      public/images/GSIcon.jpg
  - site:     https://github.com/jhollist
    img:      public/images/github-11-128.png

github:
  repo:           

#Plugins
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap