# Dependencies
markdown:         kramdown
kramdown:
  parse_block_html: true 
# highlighter:      pygments

# Permalinks
permalink:            date
paginate_path:        /page:num
# relative_permalinks:  true

# Setup
title:            'Joseph Stachelek'
tagline:          ''
description:      'Landscape Ecology, Estuarine Science, GIS, Global Climatic Change'
url:              http://jsta.github.io
baseurl:          /

author:
  name:           'Joseph Stachelek'
  url:            https://twitter.com/jjstache

paginate:         5

timezone:         America/New_York

# Custom vars
version:          0.2.0

logos:
  - site:     https://twitter.com/jjstache
    img:      public/images/Twitter_logo_blue.png
  - site:     http://scholar.google.com/citations?user=IkYbVz8AAAAJ&hl=en
    img:      public/images/GSIcon.jpg
  - site:     https://github.com/jsta
    img:      public/images/github-11-128.png

github:
  repo:           

#Plugins
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-paginate
