# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Joseph Stachelek
tagline:          ''
description:      'Landscape Ecology, Estuarine Science, GIS, Global Climatic Change'
url:              http://jsta.github.io
baseurl:          /

author:
  name:           'Joseph Stachelek'
  url:            https://twitter.com/jjstache

paginate:         5

logos:
  - site: http://twitter.com/jjstache
  img: public/images/Twitter_logo_blue.png
  - site: http://scholar.google.com/citations?user=IkYbVz8AAAAJ&hl=en
  img: public/images/GSIcon.jpg
  - site: https://github.com/jsta
  img: public/images/github-11-128.png
